//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPLMPackService.PLMPack {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PLMPack.IPLMPackService")]
    public interface IPLMPackService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLMPackService/UserDescription", ReplyAction="http://tempuri.org/IPLMPackService/UserDescriptionResponse")]
        string UserDescription();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPLMPackService/UserDescription", ReplyAction="http://tempuri.org/IPLMPackService/UserDescriptionResponse")]
        System.Threading.Tasks.Task<string> UserDescriptionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPLMPackServiceChannel : TestPLMPackService.PLMPack.IPLMPackService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PLMPackServiceClient : System.ServiceModel.ClientBase<TestPLMPackService.PLMPack.IPLMPackService>, TestPLMPackService.PLMPack.IPLMPackService {
        
        public PLMPackServiceClient() {
        }
        
        public PLMPackServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PLMPackServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PLMPackServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PLMPackServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UserDescription() {
            return base.Channel.UserDescription();
        }
        
        public System.Threading.Tasks.Task<string> UserDescriptionAsync() {
            return base.Channel.UserDescriptionAsync();
        }
    }
}
