//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMPackModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public Component()
        {
            this.MajorationSet = new HashSet<MajorationSet>();
            this.ParamDefaultComponent = new HashSet<ParamDefaultComponent>();
        }
    
        public string Guid { get; set; }
        public string DocumentId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual ICollection<MajorationSet> MajorationSet { get; set; }
        public virtual ICollection<ParamDefaultComponent> ParamDefaultComponent { get; set; }
    }
}
