//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMPackModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.TreeNodeDocuments = new HashSet<TreeNodeDocument>();
            this.Components = new HashSet<Component>();
            this.Issues = new HashSet<Issue>();
            this.UserDownloads = new HashSet<UserDownload>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DocumentType { get; set; }
        public string FileGuid { get; set; }
        public string GroupId { get; set; }
    
        public virtual File File { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<TreeNodeDocument> TreeNodeDocuments { get; set; }
        public virtual ICollection<Component> Components { get; set; }
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual ICollection<UserDownload> UserDownloads { get; set; }
    }
}
