//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMPackModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.CardboardFormats = new HashSet<CardboardFormat>();
            this.CardboardProfiles = new HashSet<CardboardProfile>();
            this.Documents = new HashSet<Document>();
            this.TreeNodeGroupShares = new HashSet<TreeNodeGroupShare>();
            this.TreeNodes = new HashSet<TreeNode>();
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.AspNetUsers1 = new HashSet<AspNetUser>();
            this.ParamDefaultComponents = new HashSet<ParamDefaultComponent>();
        }
    
        public string Id { get; set; }
        public string GroupName { get; set; }
        public string GroupDesc { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<CardboardFormat> CardboardFormats { get; set; }
        public virtual ICollection<CardboardProfile> CardboardProfiles { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<TreeNodeGroupShare> TreeNodeGroupShares { get; set; }
        public virtual ICollection<TreeNode> TreeNodes { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers1 { get; set; }
        public virtual ICollection<ParamDefaultComponent> ParamDefaultComponents { get; set; }
    }
}
