//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMPackModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int Id { get; set; }
        public string UserNoteId { get; set; }
        public string DocumentId { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public string Title { get; set; }
    
        public virtual UserNote UserNote { get; set; }
        public virtual Document Document { get; set; }
    }
}
