//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMPackModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MajorationSet
    {
        public MajorationSet()
        {
            this.Majorations = new HashSet<Majoration>();
        }
    
        public string Id { get; set; }
        public string ComponentGuid { get; set; }
        public int CardboardProfileId { get; set; }
        public string GroupId { get; set; }
    
        public virtual CardboardProfile CardboardProfile { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<Majoration> Majorations { get; set; }
        public virtual Component Components { get; set; }
    }
}
