//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMPackModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLMPackEntities : DbContext
    {
        public PLMPackEntities()
            : base("name=PLMPackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CardboardFormat> CardboardFormats { get; set; }
        public virtual DbSet<CardboardProfile> CardboardProfiles { get; set; }
        public virtual DbSet<CardboardQuality> CardboardQualities { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Issue> Issues { get; set; }
        public virtual DbSet<Majoration> Majorations { get; set; }
        public virtual DbSet<MajorationSet> MajorationSets { get; set; }
        public virtual DbSet<ParamDefaultComponent> ParamDefaultComponents { get; set; }
        public virtual DbSet<Thumbnail> Thumbnails { get; set; }
        public virtual DbSet<TreeNodeDocument> TreeNodeDocuments { get; set; }
        public virtual DbSet<TreeNodeGroupShare> TreeNodeGroupShares { get; set; }
        public virtual DbSet<TreeNode> TreeNodes { get; set; }
        public virtual DbSet<UserConnection> UserConnections { get; set; }
        public virtual DbSet<UserDownload> UserDownloads { get; set; }
        public virtual DbSet<UserGroupMembership> UserGroupMemberships { get; set; }
        public virtual DbSet<UserNote> UserNotes { get; set; }
    }
}
