//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMPackModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeNode
    {
        public TreeNode()
        {
            this.TreeNodeDocuments = new HashSet<TreeNodeDocument>();
            this.TreeNodeGroupShare = new HashSet<TreeNodeGroupShare>();
            this.Childrens = new HashSet<TreeNode>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ThumbnailId { get; set; }
        public string ParentNodeId { get; set; }
        public string GroupId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<TreeNodeDocument> TreeNodeDocuments { get; set; }
        public virtual ICollection<TreeNodeGroupShare> TreeNodeGroupShare { get; set; }
        public virtual Thumbnail Thumbnail { get; set; }
        public virtual TreeNode ParentNode { get; set; }
        public virtual ICollection<TreeNode> Childrens { get; set; }
    }
}
