//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMPackModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDownload
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string DocumentId { get; set; }
        public System.DateTime DateDownload { get; set; }
        public string FileFormat { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Document Document { get; set; }
    }
}
